"use client";

import { TwoFactorAuth } from "@/components/auth/2FA";
import { PasswordStep } from "@/components/Settings/2FASetting/EnableSteps/PasswordStep";
import { QrCodeStep } from "@/components/Settings/2FASetting/EnableSteps/QrCodeStep";
import { FeedHeader } from "@/components/Feed/FeedHeader";
import { ReturnBack } from "@/components/ui/ReturnBack";
import { Button } from "@/components/ui/button";
import { useColor } from "@/context/ColorContext";
import { authClient } from "@/lib/auth-client";
import { cn } from "@/lib/utils";
import { useState } from "react";

export const ManageTwoFactorAuthPage = () => {
    const [step, setStep] = useState(0);
    const { colors } = useColor();
    const [qrCode, setQrCode] = useState<string | null>(null);
    const { data } = authClient.useSession();

    const is2FAEnabled = data?.user?.twoFactorEnabled;

    const getDescriptionText = () => {
        if (is2FAEnabled) {
            return "You're about to disable two-factor authentication. This will remove the extra layer of security from your account.";
        } else {
            if (step === 1) return "Scan the QR code below with your authenticator app.";

            if (step === 2) return "Enter the 6-digit code generated by your authenticator app to confirm enabling two-factor authentication.";

            return "Make your account more secure by enabling two-factor authentication. To enable 2FA, you'll need to provide your password.";
        }
    }

    const steps = is2FAEnabled ?
        [
            <PasswordStep />,
        ] :
        [
            <PasswordStep setStep={setStep} setQrCode={setQrCode} />,
            <QrCodeStep value={qrCode || ""} setStep={setStep} />,
            <TwoFactorAuth>
                <Button
                    type="submit"
                    className={cn("max-w-fit text-white self-end font-bold rounded-full px-4 mt-4 hover:cursor-pointer", colors.color, colors.hoverColor)}>
                    Confirm
                </Button>
            </TwoFactorAuth>
        ];

    return (
        <div>
            <FeedHeader styles="border-b-0">
                <ReturnBack />
                <h1 className="text-xl font-bold">{is2FAEnabled ? "Disable Two-factor Authentication" : "Enable Two-factor Authentication"}</h1>
            </FeedHeader>
            <p className="text-zinc-500 text-sm mt-6 px-8">{getDescriptionText()}</p>
            <div className="p-8 flex flex-col">
                {steps[step]}
            </div>
        </div>
    )
}